### PR TITLE
Added the footer

### LINKED ISSUE #7: [UI] create Footer
NO footer

make footer

### PR DESCRIPTION
**Pull request by debjani1413**
Signed-off-by: debjani1413 <deydebjani916@gmail.com>

**Description**
Added the footer
This PR fixes #7 

**Notes for Reviewers**

**[Signed commits](https://github.com/TemplateRun/TemplateRun.io/blob/main/CONTRIBUTING.md)**

- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by debo19 — COMMENTED** [review]
footer
The footer is not responsive at this level

**Comment by debo19** [comment]
Also, I think some changes to the styles have affected the navbar logo.

**Comment by warunicorn19** [comment]
@debo19 yes it appears to be like that.

**Comment by warunicorn19** [comment]
@debjani1413 merging this though, let's create issues and assign so that everyone can get involved.

**Review by warunicorn19 — APPROVED** [review]

**Comment by warunicorn19** [comment]
@debjani1413 really great job🙏

**Pull request merged**
